name: Apply label in pull requests 

on:
  pull_request:
    types: [opened]

jobs:
  apply-label:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/github-script@v3
        if: contains(github.head_ref, 'next-release-')
        with:
          github-token: ${{github.token}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Release']
            })
