# This is a basic workflow to help you get started with Actions

name: Actions validation pull-request

on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - name: Get head ref
        run: echo "Base branch of PR ${{github.head_ref}}"
      - name: Create Label
        if: github.head_ref == "next-release-*"
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Release']
            })
