# This is a basic workflow to help you get started with Actions

name: Actions validation pull-request

on:
  pull_request_target:
    types: [opened]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
        # extract branch name on pull request
      - name: Extract branch name
        if: github.event_name == 'pull_request'
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"
  
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Release']
            })
